---
title: Expected Errors
excerpt: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore.
bottomNavigation: pagination
---

In this guide you will learn:

- How Effect represents expected errors
- The tools Effect provides for robust and comprehensive error management

As we saw in the guide [Creating Effects](../essentials/creating-effects), we can use the `fail` constructor to create an Effect
that represents an error:

```ts file=<rootDir>/src/guide/error-management/expected-errors/fail.ts

```

<Info>
  We use a class to represent the `HttpError` type above simply to gain access
  to both the error type and a free constructor. However, you can use whatever
  you like to model your error types.
</Info>

It's worth noting that we added a readonly `_tag` field as discriminant to our error in the example:

```ts /readonly _tag/ file=<rootDir>/src/guide/error-management/expected-errors/fail.ts#L3-L5

```

<Idea>
  Adding a discriminant field, such as `_tag`, can be beneficial for
  distinguishing between different types of errors during error handling. It
  also prevents TypeScript from unifying types, ensuring that each error is
  treated uniquely based on its discriminant value.
</Idea>

Expected errors **are tracked at the type level** by the `Effect` data type in the "Error" channel.

It is evident from the type of `program` that can fail with an error of type `HttpError`:

```ts /HttpError/
Effect<never, HttpError, never>
```

## Error Tracking

The following program serves as an illustration of how errors are automatically tracked for you:

<Tabs>
<Tab>

```ts filename="error-tracking.ts" file=<rootDir>/src/guide/error-management/expected-errors/error-tracking-gen.ts

```

In the above program, we compute two values: `foo` and `bar`, each representing a potential source of error.

</Tab>
<Tab>

```ts filename="error-tracking.ts" file=<rootDir>/src/guide/error-management/expected-errors/error-tracking.ts

```

In the above program, we have two operations: `flakyFoo` and `flakyBar`, each representing a potential source of error.
These operations are combined using the `Effect.all(effects){:ts}` function from the Effect library, which allows us to sequence them together.

</Tab>
</Tabs>

Effect automatically keeps track of the possible errors that can occur during the execution of the program.
In this case, we have `FooError` and `BarError` as the possible error types.
The error channel of the `program` is specified as

```ts /FooError | BarError/
Effect<never, FooError | BarError, string>
```

indicating that it can potentially fail with either a `FooError` or a `BarError`.

## Short-Circuiting

When working with APIs like `Effect.gen`, `Effect.map`, `Effect.flatMap`, and `Effect.all`, it's important to understand how they handle errors.
These APIs are designed to **short-circuit the execution** upon encountering the **first error**.

What does this mean for you as a developer? Well, let's say you have a chain of operations or a collection of effects to be executed in sequence. If any error occurs during the execution of one of these effects, the remaining computations will be skipped, and the error will be propagated to the final result.

In simpler terms, the short-circuiting behavior ensures that if something goes wrong at any step of your program, it won't waste time executing unnecessary computations. Instead, it will immediately stop and return the error to let you know that something went wrong.

<Tabs>
<Tab>

```ts file=<rootDir>/src/guide/error-management/expected-errors/short-circuiting-gen.ts

```

</Tab>
<Tab>

```ts file=<rootDir>/src/guide/error-management/expected-errors/short-circuiting-pipe.ts

```

</Tab>
</Tabs>

This code snippet demonstrates the short-circuiting behavior when an error occurs.
Each operation depends on the successful execution of the previous one.
If any error occurs, the execution is short-circuited, and the error is propagated.
In this specific example, `task3` is never executed because an error occurs in `task2`.

## Catching all Errors

<Tabs>
<Tab>

The `Effect.either` function converts an `Effect<R, E, A>` into another effect where both its failure (`E`) and success (`A`) channels have been lifted into an [`Either<E, A>`](../../other/data-types/either) data type:

```ts
Effect<R, E, A> -> Effect<R, never, Either<E, A>>
```

The [`Either<E, A>`](../../other/data-types/either) data type represents a value that can be either an error (`E`) or a successful result (`A`).
By yielding an `Either`, we gain the ability to "pattern match" on this type to handle both failure and success cases within the generator function.

```ts /Effect.either/ file=<rootDir>/src/guide/error-management/expected-errors/catch-all-gen.ts

```

We can make the code less verbose by using the `Either.match` function, which directly accepts the two callback functions for handling errors and successful values:

```ts file=<rootDir>/src/guide/error-management/expected-errors/catch-all-gen-match.ts

```

</Tab>
<Tab>

The `catchAll` function allows you to catch any error that occurs in the program and provide a fallback.

```ts {6} file=<rootDir>/src/guide/error-management/expected-errors/catch-all-pipe.ts

```

</Tab>
</Tabs>

We can observe that the type in the error channel of our program has changed to `never`,
indicating that all errors has been handled.

```ts /never/2
Effect<never, never, string>
```

## Catching Some Errors

Suppose we want to handle a specific error, such as `FooError`.

<Tabs>
<Tab>

```ts {9-11} file=<rootDir>/src/guide/error-management/expected-errors/catch-error-gen.ts

```

We can observe that the type in the error channel of our program has changed to only show `BarError`,
indicating that `FooError` has been handled.

```ts /BarError/
Effect<never, BarError, string>
```

If we also want to handle `BarError`, we can easily add another case to our code:

```ts {12} file=<rootDir>/src/guide/error-management/expected-errors/catch-error-gen-2.ts

```

We can observe that the type in the error channel of our program has changed to `never`,
indicating that all errors has been handled.

</Tab>
<Tab>

If we want to catch and recover from only some types of errors and effectfully attempt recovery, we can use the `Effect.catchSome` function:

```ts /FooError | BarError/ file=<rootDir>/src/guide/error-management/expected-errors/catchSome.ts

```

In the code above, `Effect.catchSome` takes a function that examines the error (`error`) and decides whether to attempt recovery or not. If the error matches a specific condition, recovery can be attempted by returning `Option.some(effect)`. If no recovery is possible, you can simply return `Option.none()`.

It's essential to understand that while `Effect.catchSome` allows you to catch specific errors, it **cannot reduce or eliminate the error type** itself. In other words, the resulting effect (`recovered` in this case) will still have the same error type (`FooError | BarError`) as the original effect.

However, if your program's errors are all tagged with a `_tag` field that acts as a discriminator, there is a solution. You can use the `Effect.catchTag` function to catch and handle specific errors with precision.

```ts {6-8} file=<rootDir>/src/guide/error-management/expected-errors/catch-error-pipe.ts

```

In the example above, the `Effect.catchTag` function allows us to handle `FooError` specifically.
If a `FooError` occurs during the execution of the program, the provided error handler function will be invoked,
and the program will proceed with the recovery logic specified within the handler.

We can observe that the type in the error channel of our program has changed to only show `BarError`,
indicating that `FooError` has been handled.

```ts /BarError/
Effect<never, BarError, string>
```

If we also wanted to handle `BarError`, we can simply add another `catchTag`:

```ts {9-11} file=<rootDir>/src/guide/error-management/expected-errors/catch-error-pipe-2.ts

```

We can observe that the type in the error channel of our program has changed to `never`,
indicating that all errors has been handled.

<Warning>
  It is important to ensure that the error type used with `catchTag` has a
  `readonly _tag` discriminant field. This field is required for the matching
  and handling of specific error tags.
</Warning>

Instead of using the `Effect.catchTag` function multiple times to handle individual error types, we have a more convenient option called `Effect.catchTags`. With `Effect.catchTags`, we can handle multiple errors in a single block of code.

```ts {6-9} file=<rootDir>/src/guide/error-management/expected-errors/catch-errors-pipe.ts

```

In the above example, instead of using `Effect.catchTag` multiple times to handle individual errors, we utilize the `Effect.catchTags` combinator.
This combinator takes an object where each property represents a specific error `_tag` (`"FooError"` and `"BarError"` in this case),
and the corresponding value is the error handler function to be executed when that particular error occurs.

<Warning>
  It is important to ensure that all the error types used with
  `Effect.catchTags` have a `readonly _tag` discriminant field. This field is
  required for the matching and handling of specific error tags.
</Warning>

</Tab>
</Tabs>
