import { Info, Idea, Error } from "@/components/Callout"

# Creating Effects

Effect provides different ways to create effects. In this tutorial, we will cover some of the common ones that you can use.

## From a value

To create an `Effect` from a value, you can use the `Effect.succeed` constructor:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, never, number>
const program = Effect.succeed(42)
```

The `program` value has the type `Effect<never, never, number>` and can be interpreted as an effect that:

- does not require any context (`never`)
- does not produce any expected error (`never`)
- succeeds with a value of type `number`

## From an error

To create an `Effect` that represents an error, you can use the `Effect.fail` constructor:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, string, never>
const program = Effect.fail("my error")
```

The `program` value has the type `Effect<never, string, never>` and can be interpreted as an effect that:

- does not require any context (`never`)
- fails with an expected error of type `string`
- does not produce any value (`never`)

## From a "thunk"

In JavaScript, you can defer a synchronous computation using a "thunk".

<Info>
  A "thunk" is a function that takes no arguments and may return some value.
</Info>

Thunks are useful for delaying the computation of a value until it is needed.

You can create an `Effect` from a thunk using the `Effect.sync` constructor:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, never, number>
const program = Effect.sync(() => {
  console.log("Hello, World!")
  return 42
})
```

In the above example, `Effect.sync` is used to defer the side-effect of writing to the console.
The `program` value has the type `Effect<never, never, number>` because the thunk returns the value `42`.

Note that nothing is logged to the console yet when you inspect it.
This is because `program` represents the action of writing to the console, but nothing happens until you explicitly run your program.

<Error>The thunk passed to `sync` should never throw errors.</Error>

If the synchronous computation within the thunk may throw an error, you can use the `Effect.try(thunk){:ts}` constructor.
If an error is caught, it will be propagated to the error channel as `unknown`:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, unknown, any>
const program = Effect.try(
  () => JSON.parse("") // JSON.parse may throw for bad input
)
```

If you want more control over what gets propagated to the error channel, you can use an overload of `Effect.try` that takes a remapping function:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, Error, any>
const program = Effect.try({
  try: () => JSON.parse(""), // JSON.parse may throw for bad input
  catch: (unknown) => new Error(`something went wrong ${unknown}`), // remap the error
})
```

You can think of this as a similar pattern to the traditional try-catch block in JavaScript:

```ts
try {
  return JSON.parse("")
} catch (unknown) {
  throw new Error(`something went wrong ${unknown}`)
}
```

## From a Promise

If you're dealing with asynchronous side effects that return a `Promise`, you can use the `Effect.promise` constructor:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, never, number>
const program = Effect.promise(() => Promise.resolve(42))
```

<Error>The `Promise` passed to `promise` should never reject.</Error>

If the `Promise` within the thunk may reject, you can use the `Effect.tryPromise(thunk){:ts}`constructor.
If an error is caught, it will be propagated to the error channel as `unknown`:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, unknown, Response>
const program = Effect.tryPromise(() =>
  fetch("https://jsonplaceholder.typicode.com/todos/1")
)
```

If you want more control over what gets propagated to the error channel, you can use an overload of `Effect.tryPromise` that takes a remapping function:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, Error, Response>
const program = Effect.tryPromise({
  try: () => fetch("https://jsonplaceholder.typicode.com/todos/1"),
  catch: (unknown) => new Error(`something went wrong ${unknown}`), // remap the error
})
```

## From a callback

Sometimes you have to work with APIs that don't support `async/await` or `Promise` and instead use the callback style.
To handle callback-based APIs, Effect provides the `Effect.async` constructor.

For example, let's wrap the `readFile` async API from the Node.js `fs` module with Effect:

```ts
import * as Effect from "@effect/io/Effect"
import * as NodeFS from "node:fs"

// Effect<never, NodeJS.ErrnoException, Buffer>
const program = Effect.async<never, NodeJS.ErrnoException, Buffer>((resume) => {
  NodeFS.readFile("todos.txt", (error, data) => {
    if (error) {
      resume(Effect.fail(error))
    } else {
      resume(Effect.succeed(data))
    }
  })
})
```

In the above example, we manually annotate the types when calling `Effect.async` because TypeScript cannot infer the type parameters for a callback
based on the return value inside the callback body. Annotating the types ensures that the values provided to `resume` match the expected types.

<Idea>
  You can seamlessly mix synchronous and asynchronous code within the Effect
  framework. Everything becomes an Effect, enabling you to handle different
  types of side effects in a unified way.
</Idea>

## Cheatsheet

The table provides a summary of the available constructors, along with their input and output types, allowing you to choose the appropriate function based on your needs.

| **Function**            | **Given**                          | **To**                      |
| ----------------------- | ---------------------------------- | --------------------------- |
| `succeed`               | `A`                                | `Effect<never, never, A>`   |
| `fail`                  | `E`                                | `Effect<never, E, never>`   |
| `sync`                  | `() => A`                          | `Effect<never, never, A>`   |
| `try`                   | `() => A`                          | `Effect<never, unknown, A>` |
| `try` (overload)        | `() => A`, `unknown => E`          | `Effect<never, E, A>`       |
| `tryPromise`            | `() => Promise<A>`                 | `Effect<never, unknown, A>` |
| `tryPromise` (overload) | `() => Promise<A>`, `unknown => E` | `Effect<never, E, A>`       |
| `async`                 | `Effect<never, E, A> => void`      | `Effect<never, E, A>`       |

You can find the complete list of constructors [here](https://effect-ts.github.io/io/modules/Effect.ts.html#constructors).

Now that we know how to create effects, it's time to learn how to run them.
Check out the next tutorial on [Running Effects](running) to find out more.
