# Exit

An `Exit<E, A>` describes the result of executing an `Effect` workflow.

There are two possible values for an `Exit<E, A>`:

- `Exit.Success` contains a success value of type `A`.
- `Exit.Failure` contains a failure [`Cause`](cause) of type `E`.

To handle the different outcomes of an `Exit`, we can use the `match` function:

```ts
import * as Exit from "@effect/io/Exit"

Exit.match(
  Exit.succeed(1),
  // onFailure
  (cause) => console.error(`Exited with failure state: ${cause}`),
  // onSuccess
  (value) => console.log(`Exited with success value: ${value}`)
)
// Output: Exited with success value: 1
```

By using `match`, we can provide callbacks that handle the failure case and the success case. In this example, since the `Exit` is a success, the corresponding success callback is executed, printing the success value of `1`.

## Exit vs Either

An `Exit<E, A>` is conceptually an `Either<Cause<E>, A>`. However, it's important to note that [`Cause`](cause) encompasses more states than just the expected error type `E`. It also includes other states such as interruption and defects (unexpected errors), as well as the possibility of combining multiple `Cause` values together.
